version: '3'
services:
  # Servicio MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  # Servicio para la aplicación Java
  app:
    build: ./app
    container_name: java_app
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DB: supermercado
      MONGO_USER: root
      MONGO_PASSWORD: password
    volumes:
      - ./app:/usr/src/app
    command: ["java", "-jar", "/usr/src/app/app.jar"]

volumes:
  mongodb_data:
