version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  rese単as-service
    image: rese単as:latest
    container_name: rese単as-service
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=rese単asdb
    ports:
      - "8081:8081"
    networks:
      - app-network

  ventas-service:
    image: ventas:latest
    container_name: ventas-service
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=ventasdb
    ports:
      - "8082:8082"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
